Everything to single bash script

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -14,10 +14,7 @@ inputs:
   to_branch:
     default: 'gh-pages'
     type: string
-  to_path_component:
-    default: 'component'
-    type: string
-  to_path_central:
+  to_path:
     default: 'central'
     type: string
   max_retries:
@@ -29,64 +26,37 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Deploy component repo
+    - name: Add component to main repository
       run: |
-        gh workflow run deploy-component-repo.yaml \
-        --repo "${ACTION_REPOSITORY}" \
-        --ref "${ACTION_REF}" \
-        --raw-field "from_repository=${{ inputs.from_repository }}" \
-        --raw-field "from_version=${{ inputs.from_version }}" \
-        --raw-field "to_repository=${{ inputs.to_repository }}" \
-        --raw-field "to_branch=${{ inputs.to_branch }}" \
-        --raw-field "to_path_component=${{ inputs.to_path_component }}" \
-        --raw-field "token=${{ inputs.token }}";
-        sleep 3;
-        printf "DEPLOY_RUNID=%q\n" "$(gh run list --workflow=deploy-component-repo.yaml --repo "${ACTION_REPOSITORY}" --branch "${ACTION_REF}" --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
-      env:
-        GH_TOKEN: ${{ inputs.token }}
-        ACTION_REPOSITORY: ${{ github.action_repository }}
-        ACTION_REF: ${{ github.action_ref }}
-      shell: bash
-    - name: Retry deploy component repo until finished
-      run: |
+        mkdir -p "${{ runner.temp }}/{rpm,component-repo}";
+        gh release download --repo "${{ inputs.from_repository }}" --pattern "*.rpm" --dir "${{ runner.temp }}/rpm/" "${{ inputs.from_version }}";
+        sudo apt-get update && sudo apt-get --yes install createrepo-c;
+        createrepo_c --no-database --baseurl=https://www.github.com --location-prefix="https://github.com/${{ inputs.from_repository }}/releases/download/" --outputdir="${{ runner.temp }}/component-repo "${{ runner.temp }}/rpm";
         export retries=0;
-        while ! gh run watch "${{ env.DEPLOY_RUNID }}" --repo "${ACTION_REPOSITORY}" --exit-status && [[ "${retries}" -lt "${{ inputs.max_retries }}" ]]; do \
-        echo "Retry ${retries}/${{ inputs.max_retries }}"; \
-        gh run rerun "${{ env.DEPLOY_RUNID }}" --repo "${ACTION_REPOSITORY}"; \
-        export retries="$((retries+1))"; \
+        while true; do
+          git clone --branch "${{ inputs.to_branch }}" -- "https://oauth2:${{ inputs.token }}github.com/${{ inputs.to_repository }}.git" upstream;
+          find "upstream/${{ inputs.to_path }}/";
+          mergerepo_c --all --no-database --repo="upstream/${{ inputs.to_path }}" --repo "${{ runner.temp }}/update-repo" --outputdir "upstream/${{ inputs.to_path }}/";
+          echo '[teragrep-central-releases]
+          name=teragrep-central-releases
+          baseurl=https://raw.githubusercontent.com/${{ inputs.to_repository }}/refs/heads/${{ inputs.to_branch }}/${{ inputs.to_path }}/releases
+          gpgcheck=0
+          enabled=1' > "${{ runner.temp }}/releases/teragrep-central-releases.repo";
+
+          find "${{ runner.temp }}";
+          (
+            cd "upstream/${{ inputs.to_path }}" && \
+            git add . && \
+            git status && \
+            git commit -m "Adds ${{ inputs.from_repository }} version ${{ inputs.from_version }}" && \
+            git push;
+          ) || (
+            rm -rf upstream/;
+            export retries="$((retries+1))";
+            echo "Retries: ${retries}/${{ inputs.max_retries }};
+          )
+          if [[ "${retries}" -gt "${{ inputs.max_retries }}" ]]; then
+            echo "Max retries encountered, failing";
+            exit 1;
+          fi;
         done;
-        if [[ "${retries}" == "${{ inputs.max_retries }}" ]]; then echo "Max retries encountered, failing"; exit 1; fi;
-      env:
-        GH_TOKEN: ${{ inputs.token }}
-        ACTION_REPOSITORY: ${{ github.action_repository }}
-      shell: bash
-    - name: Update central repo
-      run: |
-        gh workflow run update-central-repo.yaml \
-        --repo "${ACTION_REPOSITORY}" \
-        --ref "${ACTION_REF}" \
-        --raw-field "to_repository=${{ inputs.to_repository }}" \
-        --raw-field "to_branch=${{ inputs.to_branch }}" \
-        --raw-field "to_path_component=${{ inputs.to_path_component }}" \
-        --raw-field "to_path_central=${{ inputs.to_path_central }}" \
-        --raw-field "token=${{ inputs.token }}";
-        sleep 3;
-        printf "UPDATE_RUNID=%q\n" "$(gh run list --workflow=update-central-repo.yaml --repo "${ACTION_REPOSITORY}" --branch "${ACTION_REF}" --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
-      env:
-        GH_TOKEN: ${{ inputs.token }}
-        ACTION_REPOSITORY: ${{ github.action_repository }}
-        ACTION_REF: ${{ github.action_ref }}
-      shell: bash
-    - name: Retry update central repo
-      run: |
-        export retries=0;
-        while ! gh run watch "${{ env.UPDATE_RUNID }}" --repo "${ACTION_REPOSITORY}" --exit-status && [[ "${retries}" -lt "${{ inputs.max_retries }}" ]]; do \
-        echo "Retry ${retries}/${{ inputs.max_retries }}"; \
-        gh run rerun "${{ env.UPDATE_RUNID }}" --repo "${ACTION_REPOSITORY}"; \
-        export retries="$((retries+1))"; \
-        done;
-        if [[ "${retries}" == "${{ inputs.max_retries }}" ]]; then echo "Max retries encountered, failing"; exit 1; fi;
-      env:
-        GH_TOKEN: ${{ inputs.token }}
-        ACTION_REPOSITORY: ${{ github.action_repository }}
-      shell: bash
